var = ['AUTH_CLIENT_SECRET',
'AZURE_COSMOSDB_ACCOUNT',
'AZURE_COSMOSDB_ACCOUNT_KEY',
'AZURE_COSMOSDB_CONVERSATIONS_CONTAINER',
'AZURE_COSMOSDB_DATABASE',
'AZURE_COSMOSDB_ENABLE_FEEDBACK',
'AZURE_COSMOSDB_MONGO_VCORE_TITLE_COLUMN',
'AZURE_OPENAI_EMBEDDING_NAME',
'AZURE_OPENAI_ENDPOINT',
'AZURE_OPENAI_KEY',
'AZURE_OPENAI_MAX_TOKENS',
'AZURE_OPENAI_MODEL',
'AZURE_OPENAI_MODEL_NAME',
'AZURE_OPENAI_RESOURCE',
'AZURE_OPENAI_SYSTEM_MESSAGE',
'AZURE_OPENAI_TEMPERATURE',
'AZURE_OPENAI_TOP_P',
'AZURE_SEARCH_ENABLE_IN_DOMAIN',
'AZURE_SEARCH_FILENAME_COLUMN',
'AZURE_SEARCH_INDEX',
'AZURE_SEARCH_KEY',
'AZURE_SEARCH_QUERY_TYPE',
'AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG',
'AZURE_SEARCH_SERVICE',
'AZURE_SEARCH_STRICTNESS',
'AZURE_SEARCH_TOP_K',
'AZURE_SEARCH_USE_SEMANTIC_SEARCH',
'AZURE_SEARCH_VECTOR_COLUMNS',
'AZURE_STORAGE_ACCOUNT_CONTAINER',
'AZURE_STORAGE_ACCOUNT_KEY',
'AZURE_STORAGE_ACCOUNT_NAME',
'DATASOURCE_TYPE',
'SCM_DO_BUILD_DURING_DEPLOYMENT',
'UI_CHAT_DESCRIPTION',
'UI_CHAT_LOGO',
'UI_CHAT_LOGO_FOOTER',
'UI_CHAT_TITLE',
'UI_FAVICON',
'UI_LOGO',
'UI_SHOW_SHARE_BUTTON',
'UI_TITLE',
'UI_TITLE_FOOTER',
'WEBSITE_HTTPLOGGING_RETENTION_DAYS']

result = [{"name": i, "value": f"$({i})"} for i in var]

import json

with open("appsettings.json", "w") as f:
    json.dump(result, f, indent=2)


